-- Criar tabela para bloqueios de horários
CREATE TABLE IF NOT EXISTS public.blocked_times (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  establishment_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  professional_id INTEGER,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  reason TEXT,
  is_full_day BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

-- Adicionar índices para melhorar performance de consultas
CREATE INDEX IF NOT EXISTS blocked_times_establishment_id_idx ON public.blocked_times(establishment_id);
CREATE INDEX IF NOT EXISTS blocked_times_professional_id_idx ON public.blocked_times(professional_id);
CREATE INDEX IF NOT EXISTS blocked_times_date_idx ON public.blocked_times(start_date, end_date);

-- Adicionar gatilho para atualizar o timestamp de updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_blocked_times_updated_at ON public.blocked_times;
CREATE TRIGGER set_blocked_times_updated_at
BEFORE UPDATE ON public.blocked_times
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Configurar RLS (Row Level Security)
ALTER TABLE public.blocked_times ENABLE ROW LEVEL SECURITY;

-- Política para SELECT - usuários só podem ver seus próprios bloqueios
CREATE POLICY blocked_times_select_policy
ON public.blocked_times
FOR SELECT
USING (auth.uid() = establishment_id);

-- Política para INSERT - usuários só podem inserir seus próprios bloqueios
CREATE POLICY blocked_times_insert_policy
ON public.blocked_times
FOR INSERT
WITH CHECK (auth.uid() = establishment_id);

-- Política para UPDATE - usuários só podem atualizar seus próprios bloqueios
CREATE POLICY blocked_times_update_policy
ON public.blocked_times
FOR UPDATE
USING (auth.uid() = establishment_id);

-- Política para DELETE - usuários só podem excluir seus próprios bloqueios
CREATE POLICY blocked_times_delete_policy
ON public.blocked_times
FOR DELETE
USING (auth.uid() = establishment_id);

-- Comentários na tabela e nas colunas
COMMENT ON TABLE public.blocked_times IS 'Tabela para armazenar bloqueios de horários para agendamentos';
COMMENT ON COLUMN public.blocked_times.id IS 'Identificador único para o bloqueio de horário';
COMMENT ON COLUMN public.blocked_times.establishment_id IS 'ID do estabelecimento (referência à tabela profiles)';
COMMENT ON COLUMN public.blocked_times.professional_id IS 'ID do profissional, NULL para bloqueio geral';
COMMENT ON COLUMN public.blocked_times.start_date IS 'Data inicial do bloqueio';
COMMENT ON COLUMN public.blocked_times.end_date IS 'Data final do bloqueio';
COMMENT ON COLUMN public.blocked_times.start_time IS 'Hora inicial do bloqueio, NULL se bloqueio for o dia inteiro';
COMMENT ON COLUMN public.blocked_times.end_time IS 'Hora final do bloqueio, NULL se bloqueio for o dia inteiro';
COMMENT ON COLUMN public.blocked_times.reason IS 'Motivo do bloqueio (opcional)';
COMMENT ON COLUMN public.blocked_times.is_full_day IS 'Indica se o bloqueio é para o dia inteiro';
COMMENT ON COLUMN public.blocked_times.created_at IS 'Data e hora de criação do registro';
COMMENT ON COLUMN public.blocked_times.updated_at IS 'Data e hora da última atualização do registro'; 