// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bdjxwbmhfxikupidhkuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkanh3Ym1oZnhpa3VwaWRoa3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODU5NDQsImV4cCI6MjA1OTM2MTk0NH0.SMzROp1jGXClHUv3Knwt9MGogDwkxcE61qmsRMGjhrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);