// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyshrzsehsxxmhzcynhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5c2hyenNlaHN4eG1oemN5bmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDU4NDksImV4cCI6MjA1OTI4MTg0OX0.L8wGN5Sz1nteudA9VhIRzVD3MGbA4daaxkVZnulyaZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);